services:
  flaskblog:
    volumes:
      - type: bind
        source: ${PWD}/db/site.db
        target: /app/flaskblog/instance/site.db
    build:
      context: .
      args:
        - EMAIL_PASS=${EMAIL_PASS}
        - EMAIL_USER=${EMAIL_USER}
        - FLASK_APP=${FLASK_APP}
        - SECRET_KEY=${SECRET_KEY}
        - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      EMAIL_PASS: ${EMAIL_PASS}
      EMAIL_USER: ${EMAIL_USER}
      FLASK_APP: ${FLASK_APP}
      SECRET_KEY: ${SECRET_KEY}
      SQLALCHEMY_DATABASE_URI: ${SQLALCHEMY_DATABASE_URI}
